# Generated by Django 3.2.13 on 2023-04-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shillstreet_user', '0003_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twitter_handle',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
