# Generated by Django 3.2.13 on 2023-05-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shillstreet_user', '0004_alter_user_twitter_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter_user_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
