import Head from "next/head"
import "../styles/globals.css"
import "antd/dist/reset.css"
import { WagmiConfig, configureChains, createConfig } from "wagmi"
import { sepolia } from "wagmi/chains"
import { getDefaultProvider } from "ethers"
import { InjectedConnector } from "wagmi/connectors/injected"
import { RainbowKitProvider, darkTheme } from "@rainbow-me/rainbowkit"
import { Provider } from "react-redux"
import store from "../redux/configureStore"
import { connectorsForWallets } from "@rainbow-me/rainbowkit"
import "@rainbow-me/rainbowkit/styles.css"
import {
    injectedWallet,
    argentWallet,
    braveWallet,
    ledgerWallet,
    trustWallet,
    imTokenWallet,
    omniWallet,
    metaMaskWallet,
    walletConnectWallet,
} from "@rainbow-me/rainbowkit/wallets"
import { publicProvider } from "@wagmi/core/providers/public"
const { chains, publicClient } = configureChains(
    [/*chain.mainnet, chain.polygon, chain.polygonMumbai,*/ sepolia],
    [publicProvider()]
)

const connectors = connectorsForWallets([
    {
        groupName: "Recommended",
        wallets: [
            injectedWallet({ chains }),
            metaMaskWallet({ chains }),
            walletConnectWallet({ chains }),
        ],
    },
    {
        groupName: "Others",
        wallets: [
            trustWallet({ chains }),
            braveWallet({ chains }),
            ledgerWallet({ chains }),
            argentWallet({ chains }),
            omniWallet({ chains }),
            imTokenWallet({ chains }),
        ],
    },
])

const wagmiConfig = createConfig({
    autoConnect: true,
    connectors,
    publicClient,
})

export default function App({ Component, pageProps }) {
    return (
        <>
            <Head>
                <title>Shill Street</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <WagmiConfig config={wagmiConfig}>
                <RainbowKitProvider chains={chains}>
                    <Provider store={store}>
                        <Component {...pageProps} />
                    </Provider>
                </RainbowKitProvider>
            </WagmiConfig>
        </>
    )
}
