import Head from "next/head"
import { AppProps } from "next/app"
import "../styles/globals.css"
import "antd/dist/reset.css"
import { WagmiConfig, configureChains, createConfig } from "wagmi"
import { sepolia } from "wagmi/chains"
import { RainbowKitProvider, Theme } from "@rainbow-me/rainbowkit"
import { Provider } from "react-redux"
import store from "../redux/configureStore"
import { connectorsForWallets } from "@rainbow-me/rainbowkit"
import "@rainbow-me/rainbowkit/styles.css"
import {
    injectedWallet,
    argentWallet,
    braveWallet,
    ledgerWallet,
    trustWallet,
    imTokenWallet,
    omniWallet,
    metaMaskWallet,
    walletConnectWallet,
} from "@rainbow-me/rainbowkit/wallets"
import { publicProvider } from "@wagmi/core/providers/public"
const { chains, publicClient } = configureChains([sepolia], [publicProvider()])

const connectors = connectorsForWallets([
    {
        groupName: "Recommended",
        wallets: [
            injectedWallet({ chains }),
            metaMaskWallet({ chains }),
            walletConnectWallet({ chains }),
        ],
    },
    {
        groupName: "Others",
        wallets: [
            trustWallet({ chains }),
            braveWallet({ chains }),
            ledgerWallet({ chains }),
            argentWallet({ chains }),
            omniWallet({ chains }),
            imTokenWallet({ chains }),
        ],
    },
])

const wagmiConfig = createConfig({
    autoConnect: true,
    connectors,
    publicClient,
})

const myCustomTheme: Theme = {
    // ... other theme settings
    blurs: {
        modalOverlay: '...',
      },
    colors: {
        accentColor: '#1DA1F2',
        accentColorForeground: 'white',        
        actionButtonBorder: '...',
        actionButtonBorderMobile: '...',
        actionButtonSecondaryBackground:"white",
        closeButton: '...',
        closeButtonBackground: '...',
        connectButtonBackground: 'white',
        connectButtonBackgroundError: '...',
        connectButtonInnerBackground: '...',
        connectButtonText: '...',
        connectButtonTextError: '...',
        connectionIndicator: '...',
        downloadBottomCardBackground: '...',
        downloadTopCardBackground: '...',
        error: '...',
        generalBorder: '...',
        generalBorderDim: '...',
        menuItemBackground: '...',
        modalBackdrop: '...',
        modalBackground:"white",
        modalBorder: '...',
        modalText:'black',
        modalTextDim: 'black',
        modalTextSecondary:"black",
        profileAction: '...',
        profileActionHover: '',
        profileForeground: '',
        selectedOptionBorder: '',
        standby: '',
    },
    fonts: {
        body: '...',
      },
    radii: {
        // ...other radii
        connectButton: '5px',
        actionButton: '5px',
        menuButton: '5px',
        modal: '5px',
        modalMobile: '5px',
      },
      shadows: {
        connectButton: '...',
        dialog: '...',
        profileDetailsAction: '...',
        selectedOption: '...',
        selectedWallet: '...',
        walletLogo: '...',
      },
    
  };

export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>Shill Street</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <WagmiConfig config={wagmiConfig}>
                <RainbowKitProvider theme={myCustomTheme} chains={chains}>
                    <Provider store={store}>
                        <Component {...pageProps} />
                    </Provider>
                </RainbowKitProvider>
            </WagmiConfig>
        </>
    )
}
