import json
from channels.generic.websocket import AsyncWebsocketConsumer
from .models import CombinedMetrics


#Creating a websocker called consumer to graph total likes generated by platform
class TweetMetricsConsumer(AsyncWebsocketConsumer):
    async def connect(self):
        await self.accept()

    async def recieve(self, text_data):
        text_data_json = json.loads(text_data)
        message = text_data_json['message']

        if message == 'request_likes':
            total_likes, _ = CombinedMetrics.objects.get_or_create(id=1)
            await self.send(json.dumps({'total_likes': total_likes.total_likes}))