# Generated by Django 4.1.7 on 2023-04-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tweets', models.IntegerField()),
                ('total_retweets', models.IntegerField()),
                ('total_likes', models.IntegerField()),
                ('total_followers', models.IntegerField()),
            ],
        ),
    ]
