# Generated by Django 3.2.13 on 2023-04-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('total_tweets', models.IntegerField()),
                ('total_retweets', models.IntegerField()),
                ('total_likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('total_followers', models.IntegerField()),
            ],
        ),
    ]
